from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import numpy as np

from app.version import __version__


def write_pdf_report(result, output_path: str | Path, exact_value: float | None = None) -> None:
    """Write a compact technical report with mesh and weight diagnostics."""
    output = Path(output_path)
    mesh_name = Path(result.mesh.vertex_file).stem
    absolute_error = None if exact_value is None else abs(result.integral - exact_value)

    with PdfPages(output) as pdf:
        _write_summary_page(pdf, result, mesh_name, absolute_error, exact_value)
        _write_mesh_page(pdf, result, mesh_name)
        _write_weights_page(pdf, result)


def _write_summary_page(pdf, result, mesh_name, absolute_error, exact_value) -> None:
    figure = plt.figure(figsize=(8.27, 11.69))
    figure.patch.set_facecolor("#f7fbfd")
    figure.text(0.08, 0.91, "CubatureApp", fontsize=25, weight="bold", color="#073b5c")
    figure.text(0.08, 0.875, "Numerical cubature report", fontsize=13, color="#426577")

    rows = [
        ("Application version", __version__),
        ("Mesh", mesh_name),
        ("Integrand", result.integrand_text),
        ("Algebraic degree (ADE)", result.degree),
        ("Integral", f"{result.integral:.16g}"),
        ("Expected value", "Not provided" if exact_value is None else f"{exact_value:.16g}"),
        ("Absolute error", "Not available" if absolute_error is None else f"{absolute_error:.6e}"),
        ("Volume", f"{float(np.sum(result.weights)):.16g}"),
        ("Quadrature points", len(result.weights)),
        ("Negative weights", int(np.count_nonzero(result.weights < 0))),
        ("Positive weights", int(np.count_nonzero(result.weights > 0))),
        ("Mesh vertices", result.n_vertices),
        ("Mesh triangles", result.n_faces),
        ("Computation time", f"{result.computation_time_s * 1000:.3f} ms"),
    ]
    table = figure.add_axes([0.08, 0.15, 0.84, 0.65])
    table.axis("off")
    rendered = table.table(cellText=rows, colLabels=["Property", "Value"], loc="center", cellLoc="left", colLoc="left")
    rendered.auto_set_font_size(False)
    rendered.set_fontsize(10)
    rendered.scale(1, 1.65)
    for (row, column), cell in rendered.get_celld().items():
        cell.set_edgecolor("#c7dce6")
        cell.set_facecolor("#dff3fb" if row == 0 else "#ffffff")
        if row == 0:
            cell.set_text_props(weight="bold", color="#073b5c")
    figure.text(0.08, 0.07, "Generated by CubatureApp", fontsize=9, color="#6c7f89")
    pdf.savefig(figure, facecolor=figure.get_facecolor())
    plt.close(figure)


def _write_mesh_page(pdf, result, mesh_name) -> None:
    figure = plt.figure(figsize=(11.69, 8.27))
    axis = figure.add_subplot(111, projection="3d")
    vertices = result.mesh.vertices
    faces = result.mesh.faces_0based()
    polygons = [vertices[face] for face in faces]
    axis.add_collection3d(Poly3DCollection(polygons, alpha=0.24, facecolor="#75bdd8", edgecolor="#24566c", linewidth=0.35))
    axis.scatter(result.nodes[:, 0], result.nodes[:, 1], result.nodes[:, 2], c=np.abs(result.weights), cmap="cividis", s=8, alpha=0.8)
    axis.set_title(f"Mesh and quadrature nodes: {mesh_name}")
    axis.set_xlabel("X")
    axis.set_ylabel("Y")
    axis.set_zlabel("Z")
    axis.auto_scale_xyz(vertices[:, 0], vertices[:, 1], vertices[:, 2])
    figure.tight_layout()
    pdf.savefig(figure)
    plt.close(figure)


def _write_weights_page(pdf, result) -> None:
    figure, axes = plt.subplots(1, 2, figsize=(11.69, 8.27))
    weights = result.weights
    axes[0].hist(weights, bins=min(30, max(8, len(weights) // 4)), color="#4ea8ca", edgecolor="#073b5c")
    axes[0].set_title("Weight distribution")
    axes[0].set_xlabel("Weight")
    axes[0].set_ylabel("Count")
    axes[1].plot(np.sort(weights), marker=".", linestyle="none", color="#e08e2c", markersize=4)
    axes[1].axhline(0, color="#667781", linewidth=0.8)
    axes[1].set_title("Sorted weights")
    axes[1].set_xlabel("Sorted index")
    axes[1].set_ylabel("Weight")
    figure.tight_layout()
    pdf.savefig(figure)
    plt.close(figure)
